server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/goal-keeper-db
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        default_shema: public
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true


security:
  oauth2:
    resource:
      filter-order: 3
  signing-key: signingkey
  encoding-strength: 256
  security-realm: goal keeper realmushka
  jwt:
    client-id: clientid
    client-secret: secret
    scope-read: read
    scope-write: write
    resource-ids: testjwtresourceid
    access_token_validity_in_seconds: 300 #5 minutes
    refresh_token_validity_in_seconds: 2592000 #one month