server:
  port: 8080

security:
  oauth2:
    resource:
      filter-order: 3
  signing-key: signingkey
  encoding-strength: 256
  security-realm: goal keeper realmushka
  jwt:
    client-id: clientid
    client-secret: secret
    grant-type: password
    scope-read: read
    scope-write: write
    resource-ids: testjwtresourceid







